####################
# Compass settings #
####################
compass-enabled: true
receive-compass-on-join: true


####################
#  Menu settings   #
####################
main-menu-title: 'Available Quests'
main-menu-size: 9